_wandb:
    value:
        cli_version: 0.21.3
        e:
            i9n73k8l9kmyrx482pvct0dzahdyrlhm:
                codePath: qwen_vision_train.py
                codePathLocal: qwen_vision_train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "451214180352"
                        used: "271526100992"
                email: jwr0218@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 149cf871740fa5ddc274636421b155ffc44a083d
                    remote: https://github.com/jwr0218/Qwen_VL_finetuning.git
                gpu: NVIDIA H100 NVL
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-82f1811d-d86f-80da-37ad-4a9ffbaa0cd9
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-f9b3ada3-3fca-aae5-b7d3-9bdbc6f883e4
                host: BVH100
                memory:
                    total: "540744826880"
                os: Linux-6.8.0-64-generic-x86_64-with-glibc2.35
                program: /workspace/Toonspace_VLM/qwen_vision_train.py
                python: CPython 3.10.12
                root: /workspace/Toonspace_VLM
                startedAt: "2025-09-15T01:45:21.374706Z"
                writerId: i9n73k8l9kmyrx482pvct0dzahdyrlhm
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
            "3":
                - 2
            "4": 3.10.12
            "5": 0.21.3
            "6": 4.56.0.dev0
            "12": 0.21.3
            "13": linux-x86_64
